- name: task variable
  hosts: local
  connection: local
  vars:
    Course: ansible
    Duration: 80HRS
    Trainer: Shiva
  tasks:
  - name: variables
    vars:
      Course: DevOps with AWS
    ansible.builtin.debug:
      msg: "Course is {{ Course }}, Duration is {{ Duration }}, Trainer is {{ Trainer }}"