- name: variables arguments
  hosts: local
  connection: local
  tasks:
  - name: variables
    ansible.builtin.debug:
      msg: "Course is {{ Course }}, Duration is {{ Duration }}, Trainer is {{ Trainer }}"