- name: loop
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: loop
    ansible.builtin.dnf:
      name: "{{ item }}" 
      state: present
    loop:
    - mysql
    - redis
    - nginx